spring:
  datasource:
    url: jdbc:mysql://localhost:3306/safescan?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: "0409"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # ?? create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

